// Render every available figure: dist/static/fig-NN.svg + dist/static/fig-NN-diagram.svg
// + figures/fig-NN.static.html preview page.
// Skips any figure whose JS file doesn't exist yet.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const distDir = resolve(root, 'dist/static');
mkdirSync(distDir, { recursive: true });

const FIGS = Array.from({ length: 14 }, (_, i) => String(i + 1).padStart(2, '0'));

function previewHtml({ id, compositionSvg, diagramSvg }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>fig-${id} (static) — bell-labs-art</title>
<link rel="stylesheet" href="../shared/style.css" />
<style>
  header { max-width: 1200px; margin: 24px auto 0; padding: 0 40px; }
  h1 { font-weight: 500; font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase; margin: 0 0 4px 0; }
  h2 { margin: 0 0 8px 0; font-weight: 500; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; opacity: 0.7; }
  .legend { font-size: 11px; opacity: 0.7; margin-bottom: 6px; letter-spacing: 0.05em; }
  section { width: min(100%, 1200px); margin: 0 auto; padding: 24px 40px; }
  .composite-strip { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0; }
  .composite-strip > div { aspect-ratio: 1; display: flex; align-items: center; justify-content: center; }
  .composite-strip > div:nth-child(1) { background: #3d2f4a; }
  .composite-strip > div:nth-child(2) { background: #2e3863; }
  .composite-strip > div:nth-child(3) { background: #000; }
  .composite-strip svg { width: 92%; height: 92%; }
  .preview-box { display: flex; align-items: center; justify-content: center; }
  .preview-box svg { width: min(85vh, 850px); height: min(85vh, 850px); }
  .diagram-box { display: flex; align-items: center; justify-content: center; padding: 20px; }
  .diagram-box svg { width: 80%; height: auto; max-height: 600px; }
  nav.figs { padding: 16px 40px; opacity: 0.7; font-size: 11px; letter-spacing: 0.05em; }
  nav.figs a { margin-right: 12px; }
</style>
</head>
<body>
<nav class="figs">${FIGS.map((f) => `<a href="fig-${f}.static.html">FIG.${f}</a>`).join('')} <a href="primitives.static.html">PRIMITIVES</a></nav>
<header>
  <h1>fig-${id} · composition + composite tests</h1>
  <p class="legend">Generated by <code>node scripts/render-all.js</code>. Transparent SVG; the page-body #444 you see is preview-only.</p>
</header>
<section>
  <h2>Composition (1600×1600, on #444)</h2>
  <div class="preview-box">${compositionSvg}</div>
</section>
<section>
  <h2>Composites against #3d2f4a, #2e3863, #000</h2>
  <p class="legend">Same SVG dropped onto three other backgrounds. Confirms full transparency and that the off-white reads on each.</p>
  <div class="composite-strip">
    <div>${compositionSvg}</div>
    <div>${compositionSvg}</div>
    <div>${compositionSvg}</div>
  </div>
</section>
<section>
  <h2>Diagram-only (tight viewBox, scalable)</h2>
  <p class="legend">This is what gets shipped as <code>dist/static/fig-${id}-diagram.svg</code> for use elsewhere.</p>
  <div class="diagram-box">${diagramSvg}</div>
</section>
</body>
</html>
`;
}

let built = 0;
let skipped = 0;
for (const id of FIGS) {
  const jsPath = resolve(root, `figures/fig-${id}.js`);
  if (!existsSync(jsPath)) {
    skipped++;
    continue;
  }
  const mod = await import(`../figures/fig-${id}.js`);
  const compositionSvg = mod.buildSVG();
  const diagramSvg = mod.buildDiagramSVG();
  writeFileSync(resolve(distDir, `fig-${id}.svg`), compositionSvg);
  writeFileSync(resolve(distDir, `fig-${id}-diagram.svg`), diagramSvg);
  writeFileSync(
    resolve(root, `figures/fig-${id}.static.html`),
    previewHtml({ id, compositionSvg, diagramSvg }),
  );
  console.log(
    `  fig-${id}  composition=${compositionSvg.length}b  diagram=${diagramSvg.length}b`,
  );
  built++;
}
console.log(`\nbuilt ${built} figures, ${skipped} pending`);
