// Renders fig-02 to:
//   dist/static/fig-02.svg          — full 1600 composition (transparent)
//   dist/static/fig-02-diagram.svg  — diagram-only, tight viewBox (transparent)
//   figures/fig-02.static.html      — preview page with composition + composite strip + diagram-only

import { mkdirSync, writeFileSync } from 'node:fs';
import { buildSVG, buildDiagramSVG } from '../figures/fig-02.js';

const distDir = new URL('../dist/static/', import.meta.url);
mkdirSync(distDir, { recursive: true });

const compositionSvg = buildSVG();
const diagramSvg = buildDiagramSVG();

writeFileSync(new URL('fig-02.svg', distDir), compositionSvg);
writeFileSync(new URL('fig-02-diagram.svg', distDir), diagramSvg);

const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>fig-02 (static) — bell-labs-art</title>
<link rel="stylesheet" href="../shared/style.css" />
<style>
  header { max-width: 1200px; margin: 24px auto 0; padding: 0 40px; }
  h1 { font-weight: 500; font-size: 13px; letter-spacing: 0.1em; text-transform: uppercase; margin: 0 0 4px 0; }
  h2 { margin: 0 0 8px 0; font-weight: 500; font-size: 12px; letter-spacing: 0.08em; text-transform: uppercase; opacity: 0.7; }
  .legend { font-size: 11px; opacity: 0.7; margin-bottom: 6px; letter-spacing: 0.05em; }
  section { width: min(100%, 1200px); margin: 0 auto; padding: 24px 40px; }
  .composite-strip { display: grid; grid-template-columns: repeat(3, 1fr); gap: 0; }
  .composite-strip > div { aspect-ratio: 1; display: flex; align-items: center; justify-content: center; }
  .composite-strip > div:nth-child(1) { background: #3d2f4a; }
  .composite-strip > div:nth-child(2) { background: #2e3863; }
  .composite-strip > div:nth-child(3) { background: #000; }
  .composite-strip svg { width: 92%; height: 92%; }
  .preview-box { display: flex; align-items: center; justify-content: center; }
  .preview-box svg { width: min(85vh, 850px); height: min(85vh, 850px); }
  .diagram-box { display: flex; align-items: center; justify-content: center; padding: 20px; }
  .diagram-box svg { width: 80%; height: auto; max-height: 600px; }
</style>
</head>
<body>
<header>
  <h1>fig-02 · Colpitts Substitution Bridge — composition + composite tests</h1>
  <p class="legend">Generated by <code>node scripts/render-fig-02.js</code>. Transparent SVG; the page-body #444 you see is preview-only.</p>
</header>

<section>
  <h2>Composition (1600×1600, on #444)</h2>
  <div class="preview-box">${compositionSvg}</div>
</section>

<section>
  <h2>Composites against #3d2f4a, #2e3863, #000</h2>
  <p class="legend">Same SVG dropped onto three other backgrounds. Confirms the SVG is fully transparent and the off-white reads on each.</p>
  <div class="composite-strip">
    <div>${compositionSvg}</div>
    <div>${compositionSvg}</div>
    <div>${compositionSvg}</div>
  </div>
</section>

<section>
  <h2>Diagram-only (tight viewBox, scalable)</h2>
  <p class="legend">This is what gets shipped as <code>dist/static/fig-02-diagram.svg</code> for use elsewhere.</p>
  <div class="diagram-box">${diagramSvg}</div>
</section>

</body>
</html>
`;

writeFileSync(new URL('../figures/fig-02.static.html', import.meta.url), html);

console.log('wrote dist/static/fig-02.svg          (' + compositionSvg.length + ' bytes)');
console.log('wrote dist/static/fig-02-diagram.svg  (' + diagramSvg.length + ' bytes)');
console.log('wrote figures/fig-02.static.html');
